apiVersion: v1
metadata:
  name: pm-fio-configmap
data: 
  job.fio: |-
    ; global settings
    [global]
    ioengine=libaio
    rw=randwrite
    direct=1 
    filename=/data/test.data
    runtime=500
    time_based=0
    iodepth=64
    size=100g
    bs=4k
    numjobs=1
    per_job_logs=1
    [4krandwrite]
    name=4krandwrite
    write_bw_log=/results/4krandwrite/bw
    write_iops_log=/results/4krandwrite/iops
    write_lat_log=/results/4krandwrite/lat
  script.sh: |-
    #!/bin/bash
    JOB_NAME=4krandwrite
    DATE_WITH_HOUR=`date "+%Y%m%d-%H"`
    DATE_WITH_TIME=`date "+%Y%m%d-%H%M%S"`
    RESULTS_DIR=/results
    FILENAME="$RESULTS_DIR/$JOB_NAME_$HOSTNAME_$DATE_WITH_HOUR.out"
    echo "set environment: `env`"
    echo "----"
    echo "Starting fio job"
    mkdir -p $RESULTS_DIR/$JOB_NAME
    #
    /usr/bin/fio /scripts/job.fio --output=$FILENAME
    echo "Done with test."
    echo "Moving file $FILENAME to host $TARGET_HOST"
    #
    #cd $RESULTS_DIR/$JOB_NAME
    #echo "Creating plots"
    #/usr/bin/fio2gnuplot -b -g -p bw*.log > bw-err.log
    #/usr/bin/fio2gnuplot -i -g -p iops*.log > iops-err.log
    #/usr/bin/fio2gnuplot -g -p lat*.log > lat-err.log
    #cd /
    echo "creating archive: $HOSTNAME-$JOB_NAME.tgz"
    tar cvzf $HOSTNAME-$JOB_NAME.tgz $RESULTS_DIR
    # 
    echo "Curling archive to $WWW_TARGET_HOST"
    curl -X POST -H "Content-Type: application/x-tar" --data-binary @/$HOSTNAME-$JOB_NAME.tgz $WWW_TARGET_HOST/$DATE_WITH_HOUR/$JOB_NAME/$HOSTNAME/$HOSTNAME-$JOB_NAME.tgz
    # 
    sleep $SLEEP_DELAY
kind: ConfigMap
