apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pm-fio-ss
spec:
  serviceName: "pm-fio-ss"
  replicas: 1
  template:
    metadata:
      labels:
        app: pm-fio
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - env:
        - name: WWW_TARGET_HOST
          value: <host ip>
        - name: SLEEP_DELAY
          value: 60m
        image: falenn/pm-fio:1.0.9
        imagePullPolicy: IfNotPresent
        name: pm-fio-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: pm-fio-ss-pvc-ceph
          mountPath: /data
        - name: pm-fio-script-configmap
          mountPath: /scripts
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: script.sh
            path: script.sh
          - key: job.fio
            path: job.fio
          name: pm-fio-configmap
        name: pm-fio-script-configmap   
  volumeClaimTemplates:
  - metadata:
      name: pm-fio-ss-pvc-ceph
      annotations:
        v1.storage.k8s.io/storage-class: ceph
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph
      resources:
        requests:
          storage: 500Gi